### ISSUE TITLE
[Bug]: How to register multiple services when using UnixDomainSockets binding

### ISSUE THREAD

**Issue by DenisDoroshko** [CoreWCF/CoreWCF#1337]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.1

### Describe expected behavior

Able to register more than one service contract 

### Describe actual behavior

When registering multiple URIs for UDS like:
```
hostBuilder.UseUnixDomainSocket(options =>
{
    options.Listen(new Uri("net.uds://" +  GetUDSFilePath1()));
    options.Listen(new Uri("net.uds://" +  GetUDSFilePath2()));
});
```
It fails later on adding base addresses to dictionary, since key is a Scheme + Port so for UDS it's always `net.uds:-1`
Problematic place for getting key for uri:
```
UriSchemeKeyedCollection.cs
protected override string GetKeyForItem(Uri item)
{
    return item.Scheme + ":" + item.Port;
}
```
Am I missing something or is it a bug?

### Which binding

UnixDomainSocketBinding

### security

None

### Which .NET version

.NET 7

### Which os platform

Windows/Linux

### Code snippet used to reproduce the issue

```c#
//Server
using System;
using System.IO;
using CoreWCF;
using CoreWCF.Configuration;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

var hostBuilder = Host.CreateDefaultBuilder(Array.Empty<string>());
hostBuilder.UseUnixDomainSocket(options =>
{
    options.Listen(new Uri("net.uds://" +  GetUDSFilePath1()));
    options.Listen(new Uri("net.uds://" +  GetUDSFilePath2()));
});

hostBuilder.ConfigureServices(services => services.AddServiceModelServices());
IHost host = hostBuilder.Build();
CoreWCF.UnixDomainSocketBinding serverBinding = new CoreWCF.UnixDomainSocketBinding(UnixDomainSocketSecurityMode.None);
serverBinding.Security.Transport.ClientCredentialType = UnixDomainSocketClientCredentialType.None;

host.UseServiceModel(builder =>
{
    builder.AddService<EchoService>();
    builder.AddServiceEndpoint<EchoService, IEchoService>(serverBinding, "net.uds://" +  GetUDSFilePath1());

    builder.AddService<Echo2Service>();
    builder.AddServiceEndpoint<Echo2Service, IEcho2Service>(serverBinding, "net.uds://" +  GetUDSFilePath2());
});
await host.RunAsync();

string GetUDSFilePath1()
{
     return Path.Combine(Path.GetTempPath(), "unix1.txt");
}
string GetUDSFilePath2()
{
     return Path.Combine(Path.GetTempPath(), "unix2.txt");
}

//Contracts
[ServiceContract]
public interface IEchoService
{
    [OperationContract]
    string Echo(string text);
}

[ServiceContract]
public interface IEcho2Service
{
    [OperationContract]
    string Echo(string text);
}

public class EchoService : IEchoService
{
    public string Echo(string text)
    {
        System.Console.WriteLine($"Received {text} from client 1!");
        return text + "1";
    }
}

public class Echo2Service : IEcho2Service
{
    public string Echo(string text)
    {
        System.Console.WriteLine($"Received {text} from client 2!");
        return text + "2";
    }
}

//Client
using System;
using System.IO;
using System.ServiceModel.Channels;
using Contract;

Console.ReadLine();
var binding = new System.ServiceModel.UnixDomainSocketBinding(System.ServiceModel.UnixDomainSocketSecurityMode.None);
binding.Security.Transport.ClientCredentialType = System.ServiceModel.UnixDomainSocketClientCredentialType.None;

var factory = new System.ServiceModel.ChannelFactory<IEchoService>(binding, new System.ServiceModel.EndpointAddress(new Uri("net.uds://" + Path.Combine(Path.GetTempPath(), "unix1.txt"))));
var channel = factory.CreateChannel();
((IChannel)channel).Open();
string result = channel.Echo("Hello there");
Console.WriteLine(result);

var factory2 = new System.ServiceModel.ChannelFactory<IEcho2Service>(binding, new System.ServiceModel.EndpointAddress(new Uri("net.uds://" + Path.Combine(Path.GetTempPath(), "unix2.txt"))));
var channel2 = factory2.CreateChannel();
((IChannel)channel2).Open();
string result2 = channel2.Echo("Hello there");
Console.WriteLine(result2);
```

**Comment by DenisDoroshko** [comment]
Changing in [UriSchemeKeyedCollection.cs](https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Primitives/src/CoreWCF/UriSchemeKeyedCollection.cs) from:
```
protected override string GetKeyForItem(Uri item)
{
    return item.Scheme + ":" + item.Port;
}
```

To:
```
protected override string GetKeyForItem(Uri item)
{
    return item.Scheme + ":" + item.AbsolutePath;
}
```
Appears to work, but unsure if that's correct fix and how it should be applied to not change/break other types of binding

@mconnew @birojnayak any chance to get this fixed in the nearest future? We would like to use this type of binding since it looks better than NetTcp in local communication in terms of performance(we implemented some kind of routing service that was available in .NET Framework to speed-up communication between clients and server, but during load tests NetTcp appears to experience degradation due to overloading network, in .NET Framework we used NetTcp+NetPipes and now we want to use NetTcp+NetUds), but this issue blocks using this type of binding

**Comment by mconnew** [comment]
There's an overload for AddService which takes a delegate for Service Options. Fix up the BaseAddresses collection there to have only the one you want and that should fix it.

**Comment by DenisDoroshko** [comment]
@mconnew 
If you are about something like this:
```
builder.AddService<EchoService>(options =>
{
    options.BaseAddresses.Clear();
    options.BaseAddresses.Add(new Uri("net.uds://" +  GetUDSFilePath1()));
}
);
```
looks like this delegate called after `UriSchemeKeyedCollection.cs` created so at the moment of calling constructor of `UriSchemeKeyedCollection.cs` we are getting all the baseAddresses from what we specified in listen and creation of `UriSchemeKeyedCollection.cs` fails with exception
Sorry if I didn't get something

**Comment by DenisDoroshko** [comment]
Also tried approach with `BaseAddressCleanupHostedService` that should clear base addresses from that issue about NamedPipe: https://github.com/CoreWCF/CoreWCF/issues/1103, but in case of UDS it appears, that at the moment of calling  `BaseAddressCleanupHostedService`  serviceBuilder.BaseAddresses are not filled(but filled later via event) so in `UriSchemeKeyedCollection.cs` still getting all of them

Because in case of NamedPipe we are adding addresses in [NetNamedPipeHostedService](https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.NetNamedPipe/src/CoreWCF/Channels/NetNamedPipeHostedService.cs#L23):
```
        public NetNamedPipeHostedService(IOptions<NetNamedPipeOptions> options, IServer server, IServiceBuilder serviceBuilder, ILoggerFactory loggerFactory)
        {
            _serverOptions = options.Value ?? new NetNamedPipeOptions();
            _loggerFactory = loggerFactory;
            foreach (var listenOptions in _serverOptions.CodeBackedListenOptions)
            {
                serviceBuilder.BaseAddresses.Add(listenOptions.BaseAddress);
            }
        }
```

But in case of UDS we do this via event that happens once ServiceBuilder opened in [UnixDomainSocketFramingOptionsSetup](https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.UnixDomainSocket/src/CoreWCF/Channels/UnixDomainSocketFramingOptionsSetup.cs#L88):
```
private void OnServiceBuilderOpening(object sender, EventArgs e)
{
    UpdateServiceBuilderBaseAddresses();
}

internal void UpdateServiceBuilderBaseAddresses()
{
    foreach (ListenOptions listenOptions in ListenOptions)
    {
        string address = listenOptions.SocketPath;
        var baseAddress = new Uri($"net.uds://{address}/");
        _logger.LogDebug($"Adding base address {baseAddress} to ServiceBuilderOptions");
        _serviceBuilder.BaseAddresses.Add(baseAddress);
    }

    ListenOptions.Clear();
}
```

Tried changing `BaseAddressCleanupHostedService` to use event and it looks to be working:
```
internal class BaseAddressCleanupHostedService : IHostedService
{
    private readonly IServiceBuilder serviceBuilder;

    public BaseAddressCleanupHostedService(IServiceBuilder serviceBuilder)
    {
        this.serviceBuilder = serviceBuilder;
        serviceBuilder.Opened += OnServiceBuilderOpening;
    }
    public Task StartAsync(CancellationToken cancellationToken) => Task.CompletedTask;
    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

    private void OnServiceBuilderOpening(object sender, EventArgs e)
    {
        this.serviceBuilder.BaseAddresses.Clear();
    }
}
```
Server config if someone else will be struggling with this:
```
//Server
using System;
using System.IO;
using CoreWCF;
using CoreWCF.Configuration;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using NetCoreServer;

var hostBuilder = Host.CreateDefaultBuilder(Array.Empty<string>());
hostBuilder.UseUnixDomainSocket(options =>
{
    options.Listen(new Uri("net.uds://" + GetUDSFilePath1()));
    options.Listen(new Uri("net.uds://" + GetUDSFilePath2()));
});

hostBuilder.ConfigureServices(services =>
{
    services.AddServiceModelServices();
    services.AddSingleton<IHostedService, BaseAddressCleanupHostedService>();
}
);
IHost host = hostBuilder.Build();
CoreWCF.UnixDomainSocketBinding serverBinding = new CoreWCF.UnixDomainSocketBinding(UnixDomainSocketSecurityMode.None);
serverBinding.Security.Transport.ClientCredentialType = UnixDomainSocketClientCredentialType.None;

host.UseServiceModel(builder =>
{
    builder.AddService<EchoService>(options =>
    {
        options.BaseAddresses.Add(new Uri("net.uds://" + GetUDSFilePath1()));
    }
    );
    builder.AddServiceEndpoint<EchoService, IEchoService>(serverBinding, "net.uds://" + GetUDSFilePath1());

    builder.AddService<Echo2Service>(options =>
    {
        options.BaseAddresses.Add(new Uri("net.uds://" + GetUDSFilePath2()));
    });
    builder.AddServiceEndpoint<Echo2Service, IEcho2Service>(serverBinding, "net.uds://" + GetUDSFilePath2());
});
await host.RunAsync();

string GetUDSFilePath1()
{
    return Path.Combine(Path.GetTempPath(), "unix1.txt");
}
string GetUDSFilePath2()
{
    return Path.Combine(Path.GetTempPath(), "unix2.txt");
}
```
@mconnew please confirm, whenever you have some time, if this approach is correct to use

**Comment by DenisDoroshko** [comment]
Another not critical use case I found when applying this workaround in our real-world application: when single service implements multiple contracts (and correspondingly has multiple addresses) then getting the same issue, and of course can be avoided by just splitting such services
Probably would be nice to allow for `UriSchemeKeyedCollection.cs` to use other logic for getting key for non-http bindings to also consider path
