### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by alberthoekstra** [CoreWCF/CoreWCF#22]
I downloaded the source and try to build the project so I experiment with the libraries.
Building the solution or a single project failed with this error log:
```
1>------ Build started: Project: CoreWCF.Primitives, Configuration: Debug Any CPU ------
1>Resource File Name = C:\Projects\CoreWCF\src\CoreWCF.Primitives\src/Resources/Strings.resx
1>C:\Projects\CoreWCF\src\Common\src\CoreWCF\ProtocolExceptionHelper.cs(18,48,18,76): error CS0117: 'SR' does not contain a definition for 'ReceiveShutdownReturnedFault'
1>C:\Projects\CoreWCF\src\Common\src\CoreWCF\ProtocolExceptionHelper.cs(23,48,23,81): error CS0117: 'SR' does not contain a definition for 'ReceiveShutdownReturnedLargeFault'
1>C:\Projects\CoreWCF\src\Common\src\CoreWCF\ProtocolExceptionHelper.cs(29,44,29,74): error CS0117: 'SR' does not contain a definition for 'ReceiveShutdownReturnedMessage'
1>CoreWCF\Channels\AddressHeader.cs(115,109,115,131): error CS0117: 'SR' does not contain a definition for 'ExpectedElementMissing'
1>CoreWCF\Dispatcher\XmlSerializerOperationFormatter.cs(29,118,29,143): error CS0117: 'SR' does not contain a definition for 'SFxDocEncodedNotSupported'
1>CoreWCF\Collections\Generic\KeyedByTypeCollection.cs(106,105,106,123): error CS0117: 'SR' does not contain a definition for 'DuplicateBehavior1'
1>CoreWCF\Collections\Generic\SynchronizedCollection.cs(84,66,84,84): error CS0117: 'SR' does not contain a definition for 'ValueMustBeInRange'
1>CoreWCF\XmlUtil.cs(25,95,25,118): error CS0117: 'SR' does not contain a definition for 'XmlLangAttributeMissing'
1>CoreWCF\Dispatcher\EndpointDispatcher.cs(19,13,19,22): warning CS0649: Field 'EndpointDispatcher.listenUri' is never assigned to, and will always have its default value null
1>CoreWCF\Dispatcher\DuplexChannelBinder.cs(17,33,17,43): warning CS0649: Field 'DuplexChannelBinder.correlator' is never assigned to, and will always have its default value null
1>CoreWCF\Dispatcher\ChannelDispatcher.cs(35,14,35,21): warning CS0169: The field 'ChannelDispatcher.session' is never used
1>CoreWCF\ServiceHostBase.cs(36,13,36,22): warning CS0169: The field 'ServiceHostBase.busyCount' is never used
1>CoreWCF\Dispatcher\ChannelDispatcher.cs(41,14,41,38): warning CS0169: The field 'ChannelDispatcher.performDefaultCloseInput' is never used
1>CoreWCF\ServiceHostBase.cs(39,68,39,90): warning CS0067: The event 'ServiceHostBase.UnknownMessageReceived' is never used
1>CoreWCF\Dispatcher\ChannelDispatcher.cs(23,25,23,29): warning CS0649: Field 'ChannelDispatcher.host' is never assigned to, and will always have its default value null
1>CoreWCF\Dispatcher\ChannelDispatcher.cs(19,55,19,67): warning CS0649: Field 'ChannelDispatcher.addressTable' is never assigned to, and will always have its default value null
1>CoreWCF\ServiceHostBase.cs(32,28,32,47): warning CS0169: The field 'ServiceHostBase.readOnlyCredentials' is never used
1>CoreWCF\ServiceHostBase.cs(35,82,35,106): warning CS0169: The field 'ServiceHostBase.endpointsByListenUriInfo' is never used
1>CoreWCF\Dispatcher\ChannelDispatcher.cs(40,18,40,36): warning CS0169: The field 'ChannelDispatcher.transactionTimeout' is never used
1>CoreWCF\Description\ServiceDescription.cs(18,50,18,71): warning CS0169: The field 'ServiceDescription._implementedContracts' is never used
1>CoreWCF\Dispatcher\DispatchRuntime.cs(51,14,51,29): warning CS0649: Field 'DispatchRuntime.preserveMessage' is never assigned to, and will always have its default value false
1>CoreWCF\Description\ServiceDescription.cs(19,37,19,56): warning CS0169: The field 'ServiceDescription._reflectedContracts' is never used
1>CoreWCF\Channels\StreamSecurityUpgradeAcceptorBase.cs(13,14,13,30): warning CS0649: Field 'StreamSecurityUpgradeAcceptorBase.securityUpgraded' is never assigned to, and will always have its default value false
1>CoreWCF\Channels\ServiceChannel.cs(25,36,25,53): warning CS0649: Field 'ServiceChannel.channelDispatcher' is never assigned to, and will always have its default value null
1>CoreWCF\ServiceHostObjectModel.cs(15,26,15,44): warning CS0169: The field 'ServiceHostObjectModel<TService>._singletonInstance' is never used
1>Done building project "CoreWCF.Primitives.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

There are a lot more ''SR' does not contain a definition for 'X'' messages, for readability I removed most of them.

I've noticed the .props and .targets files in the root of the project, but I'm not familiar with those files and can't find where those files are used.

Any chance you could explain how I could build the project?

**Comment by mconnew** [comment]
Did you follow this steps from [this](https://github.com/CoreWCF/CoreWCF/blob/master/CONTRIBUTING.md) document on how to build?

> Run dotnet restore and dotnet build from the command line inside the src folder. This builds Core WCF.

Also do you have .NET Core 2.2 installed?

**Comment by alberthoekstra** [comment]
Yes, I've got .NET Core 2.2.300 installed.
When I execute those commands dotnet restore & build same build errors occur as posted before.

**Comment by tibor19** [comment]
I just tried it on my machine with 2.2.300 and it works. Please make sure that you run dotnet restore & build from your src folder at solution level (the one containing the .sln file).

**Comment by apetrut** [comment]
@alberthoekstra I had similar issues when building the solution. I fixed them by installing all the updates for Visual Studio 2017. Check that you are running the latest version of Visual Studio 2017.

**Comment by jeffdoolittle** [comment]
I'm having similar issues trying to build on a mac.

```
/usr/local/share/dotnet/sdk/2.2.300/Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/jdoolittle/jeffdoolittle/corewcf/src/Samples/DesktopServer/DesktopServer.csproj]
/usr/local/share/dotnet/sdk/2.2.300/Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/jdoolittle/jeffdoolittle/corewcf/src/Samples/DesktopClient/DesktopClient.csproj]
  NetCoreClient -> /Users/jdoolittle/jeffdoolittle/corewcf/bin/NetCoreClient/netcoreapp2.2/NetCoreClient.dll
  Resource File Name = /Users/jdoolittle/jeffdoolittle/corewcf/src/CoreWCF.Primitives/src/Resources/Strings.resx
CoreWCF/Channels/AddressHeaderCollection.cs(28,54): error CS0117: 'SR' does not contain a definition for 'MessageHeaderIsNull0' [/Users/jdoolittle/jeffdoolittle/corewcf/src/CoreWCF.Primitives/src/CoreWCF.Primitives.csproj]
CoreWCF/Channels/AddressHeaderCollection.cs(37,54): error CS0117: 'SR' does not contain a definition for 'MessageHeaderIsNull0' [/Users/jdoolittle/jeffdoolittle/corewcf/src/CoreWCF.Primitives/src/CoreWCF.Primitives.csproj]
/Users/jdoolittle/jeffdoolittle/corewcf/src/Common/src/CoreWCF/ProtocolExceptionHelper.cs(18,48): error CS0117: 'SR' does not contain a definition for 'ReceiveShutdownReturnedFault' [/Users/jdoolittle/jeffdoolittle/corewcf/src/CoreWCF.Primitives/src/CoreWCF.Primitives.csproj]
/Users/jdoolittle/jeffdoolittle/corewcf/src/Common/src/CoreWCF/ProtocolExceptionHelper.cs(23,48): error CS0117: 'SR' does not contain a definition for 'ReceiveShutdownReturnedLargeFault' [/Users/jdoolittle/jeffdoolittle/corewcf/src/CoreWCF.Primitives/src/CoreWCF.Primitives.csproj]
/Users/jdoolittle/jeffdoolittle/corewcf/src/Common/src/CoreWCF/ProtocolExceptionHelper.cs(29,44): error CS0117: 'SR' does not contain a definition for 'ReceiveShutdownReturnedMessage' [/Users/jdoolittle/jeffdoolittle/corewcf/src/CoreWCF.Primitives/src/CoreWCF.Primitives.csproj]
...
```

**Comment by mconnew** [comment]
Based on a comment which was deleted, the samples won't compile on anything except Windows as we have a Windows. NET Framework service which demonstrates interop capability. That's probably what you are running into.

**Comment by jeffdoolittle** [comment]
Yes, I deleted my comment until I was sure I couldn't get it working. Still can't. 😉 Thanks for confirming my suspicions.

**Comment by jeffdoolittle** [comment]
So what is the plan to allow this to be built on machines not running windows?

**Comment by mconnew** [comment]
We just need to disable the Windows only sample projects on non-Windows. The actual libraries should build as there's no Windows only dependencies. Net.Tcp won't work on Linux on .Net Core 2.x as server side NegotiateStream support is only being added in .Net Core 3.0.

**Comment by alberthoekstra** [comment]
I'm running those commands from the src folder.
Just installed all available updates for VS 2017 & 2019.
I'm trying to build from my Windows 10 machine.
Still same errors :-(.

**Comment by CSharpenter** [comment]
> I'm running those commands from the src folder.
> Just installed all available updates for VS 2017 & 2019.
> I'm trying to build from my Windows 10 machine.
> Still same errors :-(.

Same Here!

**Comment by brewfreedom** [comment]
Having same issue with building from command line. 17 warnings 731 Errors all dealing with Resources. No difference between building command line or Visual Studio. Windows 10/VS 2019 16.1.1

**Comment by alberthoekstra** [comment]
Anyone got another solution?

**Comment by mconnew** [comment]
The string resources aren't being generated as part of the build which is causing the compiler error. I originally made this prototype on .NET Core 2.0 and had the string resources hooked into the build a different way which stopped working when moving to a later .NET Core version. I suspect the problem is you are building with an older version of the .NET SDK which doesn't support the implicit Directory.Build.props automatic import. Can you run `dotnet --version` to find which SDK version you are using and `dotnet msbuild -ver` to find which version of msbuild you are using? According to the [docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019) the Directory.Build.props feature was added in msbuild 15.

**Comment by alberthoekstra** [comment]
```
dotnet --version: 2.2.300
dotnet msbuild -v: 16.1.76.45076
```

If I intentionally corrupt the Directory.Build.props file, and run ```dotnet build``` (in the src folder) other errors will occur. This tells me that the actual Directory.Build.props file is used, so that isn't the problem.

Something I've noticed when I run dotnet build is the last line before the errors occur. This line contains forward slashes instead of backward slashes.
```
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 34.31 ms for C:\Projects\CoreWCF\src\Samples\NetCoreClient\NetCoreClient.csproj.
  Restore completed in 34.31 ms for C:\Projects\CoreWCF\src\CoreWCF.Http\src\CoreWCF.Http.csproj.
  Restore completed in 35.2 ms for C:\Projects\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF.NetTcp.csproj.
  Restore completed in 34.31 ms for C:\Projects\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF.Primitives.csproj.
  Restore completed in 45.92 ms for C:\Projects\CoreWCF\src\Samples\NetCoreServer\NetCoreServer.csproj.
  Restore completed in 51.16 ms for C:\Projects\CoreWCF\src\CoreWCF.NetTcp\tests\CoreWCF.NetTcp.Tests.csproj.
  Restore completed in 71.63 ms for C:\Projects\CoreWCF\src\CoreWCF.Primitives\tests\CoreWCF.Primitives.Tests.csproj.
  Restore completed in 71.63 ms for C:\Projects\CoreWCF\src\CoreWCF.Http\tests\CoreWCF.Http.Tests.csproj.
  DesktopClient -> C:\Projects\CoreWCF\src\Samples\DesktopClient\bin\Debug\DesktopClient.exe
  DesktopServer -> C:\Projects\CoreWCF\src\Samples\DesktopServer\bin\Debug\DesktopServer.exe
  NetCoreClient -> C:\Projects\CoreWCF\bin\NetCoreClient\netcoreapp2.2\NetCoreClient.dll
  Resource File Name = C:\Projects\CoreWCF\src\CoreWCF.Primitives\src/Resources/Strings.resx <--- HERE
```

I'm not sure if this might be the problem, but maybe it'll ring any bells to you.

**Comment by tibor19** [comment]
Hi @alberthoekstra,

I have just create a clean Windows 10, 1809 machine, and I installed git, .net core sdk 2.2.300, and .net framework 4.7.2 developer tools. Running dotnet build succeeds without issues. If you have .net  4.8, you will need the 4.7.2 Targeting pack, which will be installed by the .net framework 4.7.2 developer tools.

**Comment by BradBarnich** [comment]
To build on Mac I had to change https://github.com/CoreWCF/CoreWCF/blob/master/resources.targets#L91 to 0x0a (line feed)

then the resources were codegened appropriately

**Comment by alberthoekstra** [comment]
@tibor19 thanks for the effort. I’ll verify the .net framework versions you’ve mentioned. I’ll come back and let you know what the results are.

**Comment by mconnew** [comment]
@BradBarnich, that's interesting. I'll have to see if I can get it to use Environment.NewLine instead. I should be able to get that working, but it's low on my priority list right now. If you are interested in coming up with a way to have it work on Windows and *nix, feel free to create a PR.  

@alberthoekstra, in the output do you have the line which starts with "Writing resources source file"? It should contain the name of the source file that the resources are written to. Can you check if that file exists? And if it does, can you check the contents look sensible.

**Comment by alberthoekstra** [comment]
@mconnew yes, I've found the log and the file. It just contains this:

```
// Do not edit this file manually it is auto-generated during the build based on the .resx file for this project.
namespace CoreWCF
{
    internal static partial class SR
    {
#pragma warning disable 0414
    private const string s_resourceName = "FxResources.CoreWCF.Primitives.SR";
#pragma warning restore 0414
    
        internal static System.Type ResourceType => typeof(FxResources.CoreWCF.Primitives.SR);
    }
}
    
namespace FxResources.CoreWCF.Primitives
{
    internal static class SR { }
}
```

**Comment by tibor19** [comment]
Hi @BradBarnich,

What happens if you change that line to 	  
`<ResourceStringItems` Include="$(ResourceFileContents.Split('%0d%0a'))"/>`

**Comment by alberthoekstra** [comment]
> Hi @BradBarnich,
> 
> What happens if you change that line to
> `<ResourceStringItems` Include="$(ResourceFileContents.Split('%0d%0a'))"/>`

This also worked for me!

**Comment by BradBarnich** [comment]
Yeah, I think that worked too
